BG_PIC = 'space.gif'
ROCKET = 'rocketship.gif'
DSTAR  = 'deathstar.gif'
WIDTH  = 402
HEIGHT = 402
FONT = ('Arial', 14, 'bold')
SCORE_POS = (100,160)
ANGLE = 4 # angle shift in degree
SHOTS_TIL_JAM = 5
CANNONBALL_SIZE = (0.2, 0.2)
CANNONBALL_SPEED = 10 
BULLETRANGE = 100
SHIPSPEED = 1
ALTITUDE = 80
MAX_X = 120
DELAY = {'rocketship': 20,  'cannonballs': 20} # milliseconds
SCORE = {'rocketship': 1, 'deathstar':10}
TIME=10

